# Generated by Django 6.0.2 on 2026-02-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelWithIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_de', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='name_idx'), models.Index(fields=['name', 'category'], name='name_cat_idx'), models.Index(fields=['name_de'], name='name_idx_name_de'), models.Index(fields=['name_en'], name='name_idx_name_en'), models.Index(fields=['name_de', 'category'], name='name_cat_idx_name_de'), models.Index(fields=['name_en', 'category'], name='name_cat_idx_name_en')],
            },
        ),
    ]
